=== RaD/djangobook/xsl/db2latex/xsl/unicode.mapping.dtd
<?xml version="1.0" encoding="utf-8"?>
<!-- $Id: unicode.mapping.dtd,v 1.1 2005/12/05 08:19:40 rpopov Exp $ -->
<!-- DTD for XML with mapping Unicode entities to LaTeX commands -->
<!-- Author: Vitaly Ostanin <vyt@altlinux.ru> -->

<!ELEMENT mapping (character+)>

<!ELEMENT character (unicode, latex?, mathlatex?, preferred)>

<!ELEMENT unicode (#PCDATA)>

<!ELEMENT latex (#PCDATA)>

<!ELEMENT mathlatex (#PCDATA)>

<!ELEMENT preferred (#PCDATA)>

=== RaD/djangobook/xsl/db2latex/xsl/unicode.mapping.ru.xml
<?xml version="1.0"?>
<!-- $Id: unicode.mapping.ru.xml,v 1.1 2005/12/05 08:19:40 rpopov Exp $ -->
<!DOCTYPE mapping SYSTEM "unicode.mapping.dtd">
<mapping>
  <character>
    <unicode>&#x00A0;</unicode>
    <preferred>~</preferred>
  </character>
  <character>
    <unicode>&#8212;</unicode>
    <preferred>---</preferred>
  </character>
  <character>
    <unicode>&#x00AB;</unicode>
    <preferred>\guillemotleft </preferred>
  </character>
  <character>
    <unicode>&#x00BB;</unicode>
    <preferred>\guillemotright </preferred>
  </character>
  <character>
    <unicode>&#x201E;</unicode>
    <preferred>,,</preferred>
  </character>
  <character>
    <unicode>&#x201C;</unicode>
    <preferred>\textquotedblleft\space </preferred>
  </character>
  <character>
    <unicode>&#8221;</unicode>
    <preferred>\textquotedblright\space </preferred>
  </character>
</mapping>

=== RaD/djangobook/xsl/mylatex/xsl/unicode.mapping.xml
<?xml version="1.0"?>
<!-- $Id: unicode.mapping.xml,v 1.1 2005/12/05 08:19:40 rpopov Exp $ -->
<!DOCTYPE mapping SYSTEM "unicode.mapping.dtd">
<mapping>
  <character>
    <unicode>&lt;</unicode>
    <latex>\guilsinglleft </latex>
    <preferred>\guilsinglleft </preferred>
  </character>
    <character>
    <unicode>></unicode>
    <latex>\guilsinglright </latex>
    <preferred>\guilsinglright </preferred>
  </character>
  <character>
    <unicode>#</unicode>
    <latex>\#</latex>
    <preferred>\#</preferred>
  </character>
  <character>
    <unicode>$</unicode>
    <latex>\textdollar </latex>
    <mathlatex>\$</mathlatex>
    <preferred>\$</preferred>
  </character>
  <character>
    <unicode>%</unicode>
    <latex>\%</latex>
    <preferred>\%</preferred>
  </character>
  <character>
    <unicode>&amp;</unicode>
    <latex>\&amp;</latex>
    <preferred>\&amp;</preferred>
  </character>
  <character>
    <unicode>~</unicode>
    <latex>\textasciitilde </latex>
    <preferred>\textasciitilde </preferred>
  </character>
  <character>
    <unicode>_</unicode>
    <latex>\_</latex>
    <preferred>\_</preferred>
  </character>
  <character>
    <unicode>^</unicode>
    <latex>\^{}</latex>
    <preferred>\^{}</preferred>
  </character>
  <character>
    <unicode>\</unicode>
    <latex>\textbackslash </latex>
    <mathlatex>\ensuremath{\backslash} </mathlatex>
    <preferred>\ensuremath{\backslash} </preferred>
  </character>
  <character>
    <unicode>{</unicode>
    <latex>\{</latex>
    <preferred>\{</preferred>
  </character>
  <character>
    <unicode>}</unicode>
    <latex>\}</latex>
    <preferred>\}</preferred>
  </character>
  <character>
    <unicode>|</unicode>
    <latex>\ensuremath{\vert} </latex>
    <preferred>\ensuremath{\vert} </preferred>
  </character>
</mapping>
